### PR TITLE
Display the path in a collapse in the button [issue-18]

### PR DESCRIPTION
**Pull request by JaySunSyn**
See https://github.com/Neovici/cosmoz-treenode-navigator/issues/18

Display path in button:
- Swipe down/up
- Hover above left arrow icon

### CODE REVIEW

**Comment by nomego** [comment]
Sorry needs rebase

**Comment by dotpointer** [comment]
Tried to clone this branch, but it did not appear in the output of `git branch -v -a`, `git branch -r` or `git ls-remote [...]`. Seems like the branch is in JaySunSyns forked repository but the PR is on this repository.

**Comment by JaySunSyn** [comment]
@dotpointer This PR might can be closed. Not sure if it reflects current requirements for the navigator.

**Comment by dotpointer** [comment]
@JaySunSyn Ok, closing it.

**Pull request closed without merging**
