### PR TITLE
Upgrade to Polymer 3

### LINKED ISSUE #50: Upgrade to Polymer 3
Dependencies:

* [x] cosmoz-i18next https://github.com/Neovici/cosmoz-i18next/pull/24
* [x] cosmoz-dialog https://github.com/Neovici/cosmoz-dialog/pull/34
* [x] cosmoz-tree https://github.com/Neovici/cosmoz-tree/issues/20 https://github.com/Neovici/cosmoz-tree/pull/21

### PR DESCRIPTION
**Pull request by cristinecula**
Fixes #50

### CODE REVIEW

**Comment by cristinecula** [comment]
Depends on:

```
"@neovici/cosmoz-dialog": "plumelo/cosmoz-dialog#feature/NEOV-369-polymer3",
"@neovici/cosmoz-i18next": "plumelo/cosmoz-i18next#feature/NEOV-366-upgrade-polymer-3",
"@neovici/cosmoz-tree": "plumelo/cosmoz-tree#NEOV-377-polymer-3",
```

**Comment by cristinecula** [comment]
@megheaiulian @nomego

**Comment by cristinecula** [comment]
@nomego @Wurper ready to release, but build fails because of yarn cache (please re-run build with fresh cache).

**Comment by Wurper** [comment]
@cristinecula Build see mto have passed.
But needs conflict resolution.

**Comment by cristinecula** [comment]
@Wurper that's weird. I think it's a github bug, because the branch has been merged successfully:
2019-06-20-121752_1083x523_scrot

**Pull request closed without merging**
